general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
# normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
# bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
# italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
# size = 9
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 8

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
